# A Github Action that minifies html/css/js and pushes it to a new branch
name: deploy
run-name: Minify JS/CSS/HTML [gh-pages branch]

# Run on pushes to `main` branch
on:
  push:
    branches:
      - 'main'

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install CLI tools
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g terser
      - run: npm install -g postcss postcss-cli postcss-nesting cssnano
      - run: npm install -g html-minifier

      # Use CLI tools to minify, overwriting existing files
      - run: for i in ./assets/scripts/*.js; do terser $i --compress -o $i; done
      - run: npx postcss ./assets/css/styles.css --use postcss-nesting cssnano -o ./assets/css/styles.css
      - run: |
          shopt -s globstar
          for i in ./pt-BR/**/index.html; do html-minifier --collapse-boolean-attributes --remove-empty-attributes --remove-tag-whitespace --collapse-whitespace --minify-css --minify-js --minify-urls --remove-comments $i -o $i; done
      
      # Push changes to `gh-pages` branch
      - name: Push changes to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -am 'Automated minify of ${{ github.sha }}'
          git push --force -u https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main:gh-pages
